version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 16...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      - echo Testing...
      - echo Building...
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build